package asepsis.bluej.test.domain;

import asepsis.bluej.domain.Assignment;
import org.junit.Before;
import org.junit.Test;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class AssignmentTest {

    private Assignment ass;

    @Before
    public void setUp() throws Exception {
        ass = new Assignment("SomeName");
    }

    @Test
    public void getName_ReturnsName_WhenSetInConstructor() {
        assertThat(ass.getName(), is("SomeName"));
    }

    @Test
    public void toString_ReturnsDescriptiveString_WhenCalled() {
        assertThat(ass.toString(), is("Assignment{name=SomeName}"));
    }

    // equals() and hashCode() are generated by IntelliJ, so don't test anything else than equals
    @Test
    public void equals_ReturnsTrue_WhenAssignmentsHaveSameName() {
        Assignment ass2 = new Assignment("SomeName");

        assertThat(ass, is(equalTo(ass2)));
    }

    @Test(expected = IllegalArgumentException.class)
    public void constructor_ThrowsIllegalArgumentException_WhenNameIsNull() {
        new Assignment(null);
    }
}
